# Ejemplos rápidos de introducción a Julia

## Funciones

https://docs.julialang.org/en/v1/manual/functions/



In [5]:
# Sintaxis básica: function...end
function f(x,y)
    (x+y)^2
end
f(1,2)

9

In [6]:
# Sintaxis abreviada "assignment form" f(x)=
f(x,y) = (x+y)^3
f(1,1)

8

In [9]:
# Multiple Return Values
function mi_f(x,y)
    return x+y, x-y
end
mi_f(3,3)

(6, 0)

In [16]:
# Keyword Arguments
function f(x, y=3)
    x+y
end
f(1)

4

In [33]:
# Function composition and piping
(sin ∘ asin)(0.5333)

0.5333 |> asin |> sin |> x -> x^2 |> sqrt

[ x |> asin |> sin |> x -> x^2 |> sqrt  for  x in [.2, 0.3, 0.4] ]

3-element Array{Float64,1}:
 0.2
 0.3
 0.4

In [48]:
# Dot Syntax for Vectorizing Functions
#   Any Julia function f can be applied elementwise to any array (or other collection)
#   with the syntax f.(A)

v = [2 3 4]
println(log.(v))

f(x) = x^2+1
println(f.(v))

u = v
u + v
u.^2

[0.6931471805599453 1.0986122886681098 1.3862943611198906]
[5 10 17]


1×3 Array{Int64,2}:
 4  9  16

## Control de flujo

In [56]:
# Bloques de código: begin...end   /   (...)
begin
    a=2
    b=a+1
end

3

In [61]:
# Condicionales if...elseif...else...end   /   a ? b: c    /   a && b   /   a || c
if b>a
    println(" $b>$a ")
else
    println("no")
end
println("----------")
b>a ? print("sí") : print("no")

 3>2 
----------
sí

In [70]:
# Bucles  while condición ... end    /   for i = 1:n ... end
for i=-3:2:8
    print("i=$i, ")
end

i=-3, i=-1, i=1, i=3, i=5, i=7, 

In [78]:
# Excepciones y errores:  throw, try/cach, finaly
function divide_por(x)
    if x==0
        throw( "Divisón por cero" )
    end
    1/x
end
divide_por(0)

String: "Divisón por cero"

In [28]:
# Tareas o "Corrutinas" (Tasks aka Corroutines)
#   Paralelización!

## Programación Orientada a Objetos
(...)

## Arrays 

https://docs.julialang.org/en/v1/manual/arrays/

- An array is a *collection of objects stored in a multi-dimensional grid*. In the most general case, an array may contain **objects of type Any**. For most **computational purposes**, arrays **should contain objects of a more specific type**, such as **Float64** or Int32.

- In general, unlike many other technical computing languages, **Julia does not expect** programs to be written in a **vectorized style** for performance. Julia's compiler uses type inference and generates optimized code for scalar array indexing, allowing programs to be written in a style that is convenient and readable, without sacrificing performance, and using less memory at times.

- In Julia, **all arguments to functions are passed by sharing (i.e. by pointers)**. Some technical computing languages pass arrays by value, and while this prevents accidental modification by callees of a value in the caller, it makes avoiding unwanted copying of arrays difficult. **By convention, a function name ending with a !** indicates that it will mutate or destroy the value of one or more of its arguments (compare, **or example, sort and sort!*). Callees must make explicit copies to ensure that they don't modify inputs that they don't intend to change. Many non- mutating functions are implemented by calling a function of the same name with an added ! at the end on an explicit copy of the input, and returning that copy.

In [87]:
# Construction and Initialization

v = zeros(3) # v = zeros(Float64,2)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [104]:
zeros(Float64, (2,2,2)) # Tensor de dimensión 3 (vector dim 1, matrices dim 2, etc)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [105]:
println("Vectores columna!")
println(v)
println("         ^---- la coma denota separación de filas")

Vectores columna!
[0.0, 0.0, 0.0]
         ^---- la coma denota separación de filas


In [108]:
# Asignación por referencia
v = [1 2 3] # vector fila
w = v
w[1]=9
println("v = $v")
println("        ^---- espacios en blanco denotan separación de columnas")

v = [9 2 3]
        ^---- espacios en blanco denotan separación de columnas


In [114]:
# Asignación mediante copia
v = [1;2;3]
w = copy(v)
w[1]=22
println("v = $v")

w = 2v
w[1] = 3
v

for(...)
    calcular_en_función_de_u0(u1) # Solución etap m+1
    u0 = copy(u1) # Preparar la siguiente iteración

v = [1, 2, 3]


3-element Array{Int64,1}:
 1
 2
 3

In [65]:
# Array literals

In [64]:
# Comprehensions

In [66]:
# (...)